[Distribution]
Distribution=fedora
Release=43

[Build]
ExtraSearchPaths=./systemd/build/mkosi.builddir/fedora~43~x86-64/

[Config]
Profiles=desktop,kde,custom

[Output]
ManifestFormat=changelog

[Content]
VolatilePackageDirectories=./systemd/build/mkosi.builddir/fedora~43~x86-64/
