[Content]
Packages=
        # keyrings for building other distro images
        archlinux-keyring
        debian-keyring
        ansible
        ansible-collection-ansible-posix
        ansible-collection-community-postgresql
        ansible-collection-community-general
        ansible-collection-community-crypto
        python3-ansible-lint
        asciiquarium
        awk
        bash
        bash-completion
        bat
        binutils
        bind-utils
        bridge-utils
        clatd
        clang-devel
        cowsay
        cmatrix
        curl
        dictd
        diffoscope
        du-dust
        duf
        d2
        emacs
        entr
        exfatprogs
        exiftool
        fastfetch
        fcitx5-mozc
        fcitx5-configtool
        fcitx5-gtk
        fcitx5-qt
        firejail
        kcm-fcitx5
        fd-find
        file
        fish
        flatpak
        fprintd-pam
        fortune
        # needed for appimage
        fuse-libs
        fzf
        gcc
        git
        git-absorb
        git-delta
        git-lfs
        glances
        # needed for geoclue?
        glib-networking
        guestfs-tools
        golang
        graphviz
        htop
        iio-sensor-proxy
        ImageMagick
        iperf3
        java-latest-openjdk
        katago-opencl
        intel-opencl
        OpenCL-ICD-Loader
        @kde-desktop
        kde-connect
        kde-partitionmanager
        kitty
        kitty-shell-integration
        kitty-terminfo
        krfb
        libfprint-tod
        libfprint-2-tod1-broadcom
        libfprint-tod-selinux
        litecli
        lm_sensors
        lolcat
        lshw
        lsof
        man
        # include mkosi just for shell completion and man pages
        mkosi
        mokutil
        mpv
        ncdu
        neovim
        ninja
        okular
        opentofu
        osc
        # needed for bell fish function
        ocean-sound-theme
        pre-commit
        python3-neovim
        nmap
        nmap-ncat
        # for coc.nvim
        npm
        # needed for clatd on F43 apparently
        perl-IPC-Cmd
        perl-JSON
        pipewire-utils
        plasma-disks
        plasma-vault
        pnpm
        powertop
        progress
        proxychains-ng
        pv
        python3-netaddr
        restic
        autorestic
        ripgrep
        rubygem-asciidoctor
        rustup
        rsync
        sbctl
        setroubleshoot
        sbsigntools
        sqlite
        stgit
        tcpdump
        # not yet available for fedora 43
        terraform-ls
        tmux
        toolbox
        tor
        translate-shell
        trash-cli
        ttyplot
        units
        unrar-free
        @virtualization
        wget
        whois
        wl-clipboard
        wireshark
        yubikey-manager
        gnupg2-scdaemon
        kernel
        # repository directory comes from mkosi.packages
        repository/opensnitch_ui.rpm
        repository/opensnitch.rpm
        python3-grpcio+protobuf
        python3-slugify
