# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=fedora

[Content]
Packages=
        plasma-discover
        plasma-drkonqi
        plasma-print-manager
        sddm-breeze
        plasma-discover-flatpak
        plasma-discover-notifier
        plasma-firewall-firewalld
